---
title: "Visual Analysis of Hotel Bookings Dataset"
author: "Dominik Vukelic"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE)
## Importing necessary libraries
library(ggplot2)
library(tidyverse)  # Includes dplyr and forcats
library(scales)
library(ggrepel)
```

```{r}
# Load the dataset directly within the R code chunk with the full path
dataset_path <- "C:\\Users\\Hectic\\Documents\\hotel_bookings_dataset_project\\cleaned_starting_file\\hotel_bookings_cleaned.csv"

df <- read.csv(dataset_path, na.strings = c("", "NA"))
```
# Creating a pie chart with percentages for cancelations
```{r}
# Calculate percentages of cancelations using dplyr
df_percent <- df %>%
  count(is_canceled) %>%
  mutate(percentage = n / sum(n) * 100)

# Creating a pie chart with percentages for cancelations
ggplot(df_percent, aes(x = "", y = percentage, fill = is_canceled)) +
  geom_bar(stat = "identity", width = 1, color = "black") +
  coord_polar(theta = "y") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)),
            position = position_stack(vjust = 0.5)) +
  labs(title = "Cancellation Status",
       fill = "Cancellation Status") +
  scale_fill_manual(values = c("yes" = "lightpink", "no" = "lightblue")) +  # Switched colors
  theme_void()
```

